"""empty message

Revision ID: fc5079d62940
Revises: 7fe15f77cf84
Create Date: 2021-08-26 22:50:43.716609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5079d62940'
down_revision = '7fe15f77cf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('original_currency', sa.String(length=4), nullable=False),
    sa.Column('converted_amount', sa.Float(), nullable=True),
    sa.Column('converted_currency', sa.String(length=4), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('wallet')
    # ### end Alembic commands ###
